### ISSUE TITLE
Conflicting with HASmartTermostat

### ISSUE THREAD

**Issue by andreid1303** [hacker-cb/hassio-component-smart-thermostat#18]
I am using https://github.com/ScratMan/HASmartThermostat that was stated since 2021 and want to try yours but both have same name **smart_thermostat**

Upon restart I got error:
Invalid config for [climate.smart_thermostat]: [outdoor_sensor] is an invalid option for [climate.smart_thermostat]. Check: climate.smart_thermostat->outdoor_sensor. (See /var/homeassistant/.homeassistant/packages/climate.yaml, line 116). Please check the docs at https://github.com/jethome-ru/hassio-component-smart-thermostat

and my HASmartThermostat climate is not working.

**Comment by hacker-cb** [comment]
Sorry for this case, but I can't change name
